SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*ORDER BY t0.USERID, CONVERT(DATE, CHECKTIME)*/
ALTER VIEW [dbo].[vwCHECKINOUT2]
AS
SELECT t0.USERID, t1.Badgenumber AS Codigo, ISNULL(t1.Name, '') + ' ' + ISNULL(t1.lastname, '') AS Empleado, CASE DATEPART(WEEKDAY, CHECKTIME) 
                  WHEN 1 THEN 'Domingo' WHEN 2 THEN 'Lunes' WHEN 3 THEN 'Martes' WHEN 4 THEN 'Miercoles' WHEN 5 THEN 'Jueves' WHEN 6 THEN 'Viernes' WHEN 7 THEN 'Sabado' END AS Dia, CONVERT(DATE, t0.CHECKTIME) AS Fecha, 
                  CASE WHEN MIN(CHECKTIME) = MAX(CHECKTIME) THEN CASE WHEN DATEPART([hour], MIN(CHECKTIME)) < 16 THEN MIN(CHECKTIME) ELSE NULL END ELSE MIN(CHECKTIME) END AS Entrada, CASE WHEN MIN(CHECKTIME) 
                  = MAX(CHECKTIME) THEN CASE WHEN DATEPART([hour], MIN(CHECKTIME)) >= 16 THEN MAX(CHECKTIME) ELSE NULL END ELSE MAX(CHECKTIME) END AS Salida, CONVERT(varchar, MAX(t0.CHECKTIME) - MIN(t0.CHECKTIME), 108) 
                  AS HorasOficina, (CASE WHEN MIN(CHECKTIME) != MAX(CHECKTIME) THEN CASE DATEPART(WEEKDAY, t0.CHECKTIME) WHEN 6 THEN (DATEDIFF(MINUTE, CONVERT(DATETIME, '08:30:00', 108), (MAX(CHECKTIME) - MIN(CHECKTIME)))) 
                  ELSE (DATEDIFF(MINUTE, CONVERT(DATETIME, '09:30:00', 108), (MAX(CHECKTIME) - MIN(CHECKTIME)))) END ELSE 0.00 END) / 60 AS Excedente
FROM     dbo.CHECKINOUT AS t0 INNER JOIN
                  dbo.USERINFO AS t1 ON t0.USERID = t1.USERID
GROUP BY CONVERT(DATE, t0.CHECKTIME), t0.USERID, ISNULL(t1.Name, '') + ' ' + ISNULL(t1.lastname, ''), t1.Badgenumber, DATENAME(WEEKDAY, t0.CHECKTIME), DATEPART(WEEKDAY, t0.CHECKTIME)
GO
