SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tNit](
	[nit] [nvarchar](24) NOT NULL,
	[nombre] [nvarchar](128) NOT NULL,
	[direccion] [nvarchar](512) NOT NULL,
	[manual] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[nit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tNit] ADD  DEFAULT ((0)) FOR [manual]
GO
